# Generated by Django 2.0.4 on 2018-04-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demowork', '0002_auto_20180412_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otdel',
            options={'ordering': ['name'], 'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
        migrations.AlterField(
            model_name='recordsdemoworks',
            name='media',
            field=models.FileField(blank=True, default='', upload_to='demowork/media', verbose_name='Файлы'),
        ),
    ]
