# Generated by Django 2.0.5 on 2018-05-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demowork', '0004_auto_20180412_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.AlterModelOptions(
            name='otdel',
            options={'ordering': ['title'], 'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
        migrations.RenameField(
            model_name='demoworks',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='otdel',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='recordsdemoworks',
            old_name='name',
            new_name='title',
        ),
    ]
