# Generated by Django 2.0.5 on 2018-05-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demowork', '0005_auto_20180515_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoworks',
            name='tags',
            field=models.ManyToManyField(to='demowork.Tag', verbose_name='Тэги'),
        ),
    ]
