# Generated by Django 2.0.5 on 2018-05-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demowork', '0006_demoworks_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demoworks',
            name='keywords',
            field=models.CharField(max_length=100, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='demoworks',
            name='tags',
            field=models.ManyToManyField(null=True, to='demowork.Tag', verbose_name='Тэги'),
        ),
    ]
